### ISSUE TITLE
カスタムコンポーネントのディレクトリ名

### ISSUE THREAD

**Issue by Chabiichi** [yutoyazaki/hass-nature-remo#1]
はじめまして。
HAへのNatureRemoの統合とても嬉しいです。Remoのエアコンのオートメーションを構成できるのはすごく便利です。

さて、私の環境だけかどうかわかりませんが、Readmeでは/config/custom_components/nature_remoとなってますが、/config/custom_components/nature-remo でないとエラーになりました。
細かいところですが、ちょっと焦ったので一応。

今後のこのコンポーネントの発展すごく期待しています。

**Comment by yutoyazaki** [comment]
@Chabiichi 
私の環境では`/config/custom_components/nature_remo`でも動いています。出力されたエラーログは記載できますでしょうか？
他にも_(アンダースコア)を使っているカスタムコンポーネントは多く存在しているため、アンダースコアが使えないということはなさそうです。もしかすると他の設定と名前が衝突しているとかはないでしょうか？

**Comment by Chabiichi** [comment]
@yutoyazaki 
こちらではコンポーネントを導入時に"Check Config"を実行したときにエラーが表示されたのですが、ログが探せませんでした。なので同じ状況にしようとディレクトリ名を"/nature_remo"に変更して”Check Config”を実行したところ、何故か正常終了しました。お騒がせしてしまって申し訳ございません。
