### ISSUE TITLE
0.5度単位で温度設定ができるエアコンでは動作しない

### ISSUE THREAD

**Issue by uniras** [yutoyazaki/hass-nature-remo#5]
おそらく0.5度単位で温度設定ができるエアコンを登録していると「ValueError: invalid literal for int() with base 10: '16.5'」といったエラーが出てintegrationそのものが動かないようです。

ちなみに自分がこのエラーに遭遇したmodelは
```
    "model": {
      "id": "これを晒していいのかどうかわからないのでとりあえず隠します",
      "country": "JP",
      "manufacturer": "mitsubishi",
      "remote_name": "pg095",
      "series": "",
      "name": "Mitsubishi AC 022",
      "image": "ico_ac_1"
    },
```
です。

具体的には https://api.nature.global/1/appliances で取得したJSONのaircon.range.modes.warmまたはcoolのtempに16.5などの小数点付きの文字列が格納されるものが該当すると思われます。

climate.pyの_current_mode_temp_range関数でlist作成時にint関数でmapしているのが原因のようです。intをfloatに変えてみたら動作しました。

**Comment by yutoyazaki** [comment]
こちら0.5度単位で設定できるように対応しました！ https://github.com/yutoyazaki/hass-nature-remo/pull/6
